spring:
  application:
    name: intern-assignment
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console

jwt:
  secret: ${JWT_SECRET}

server:
  port: 8080
