name: Deploy to EC2

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    name: Build & Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant permission to gradlew
        run: chmod +x ./gradlew

      - name: Build application
        run: ./gradlew clean build -x test

      - name: Copy jar to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: build/libs/*.jar
          target: /home/${{ secrets.EC2_USER }}/app

      - name: Remote SSH - Run App on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script_stop: false
          script: |
            echo "[STEP] 종료 중인 애플리케이션 확인 및 종료"
            PID=$(pgrep -f 'java -jar')
            if [ -n "$PID" ]; then
              echo "기존 프로세스 종료: $PID"
              kill -15 $PID
              sleep 3
            fi
            
            nohup java -jar /home/${{ secrets.EC2_USER }}/app/*.jar --server.port=8081 \
              > /home/${{ secrets.EC2_USER }}/app/app.log 2>&1 < /dev/null &
            
            disown
            
            echo "[완료] 배포 시각: $(date)"

