name: SpringBoot Project CI + Coverage Upload

on:
  pull_request:
    branches:
      - dev

jobs:
  test-and-upload:
    runs-on: ubuntu-latest
    name: Run Tests & Upload Coverage Report

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant Permission to Gradlew
        run: chmod +x ./gradlew

      - name: Run Tests & Generate JaCoCo Coverage
        run: ./gradlew clean test jacocoTestReport

      - name: Upload Coverage Artifact
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: build/jacocoHtml
