name: CI + JaCoCo Coverage + GitHub Pages Deploy (dev only)

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    name: Run Tests → Generate Coverage → Deploy

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant Permission to Gradlew
        run: chmod +x ./gradlew

      - name: Run Tests & Generate JaCoCo Report
        run: ./gradlew clean test jacocoTestReport

      - name: Upload JaCoCo Report as Artifact (for PRs)
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: build/jacocoHtml

      - name: Deploy to GitHub Pages (on dev branch)
        if: github.ref == 'refs/heads/dev'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/jacocoHtml
          publish_branch: gh-pages
          force_orphan: true
