name: Deploy Coverage to GitHub Pages

on:
  workflow_run:
    workflows: ["SpringBoot Project CI + Coverage Upload"]
    types:
      - completed

jobs:
  deploy-coverage:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    name: Deploy JaCoCo Coverage

    steps:
      - name: Download coverage artifact
        uses: actions/download-artifact@v4
        with:
          name: jacoco-report
          path: coverage

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: coverage
          publish_branch: gh-pages
          force_orphan: true
